export const SEO_VOCABULARY = [
  "GSC",
  "Google Search Console",
  "GA4",
  "Ahrefs",
  "Semrush",
  "Core Update",
  "PBN",
  "Guest Post",
  "Entity",
  "backlink",
  "referring domain",
  "anchor text",
  "expired domain",
  "301 redirect",
  "canonical",
  "robots.txt",
  "sitemap",
  "indexing",
  "search intent",
  "internal link",
  "DR",
  "UR",
  "organic traffic",
  "money site",
  "keyword",
  "ranking",
  "crawl",
  "negative SEO",
  "disavow",
  "Wayback",
  "casino",
  "betting",
  "sports betting",
  "iGaming"
] as const;
