export const SEO_VOCABULARY = [
  "GSC",
  "Google Search Console",
  "GA4",
  "Ahrefs",
  "Semrush",
  "Core Update",
  "PBN",
  "Guest Post",
  "Entity",
  "backlink",
  "referring domain",
  "anchor text",
  "expired domain",
  "301 redirect",
  "canonical",
  "robots.txt",
  "sitemap",
  "indexing",
  "search intent",
  "internal link",
  "DR",
  "UR",
  "organic traffic",
  "money site",
  "keyword",
  "ranking",
  "crawl",
  "negative SEO",
  "disavow",
  "Wayback",
  "casino",
  "betting",
  "sports betting",
  "iGaming"
] as const;

export const DEEPGRAM_KEYTERMS = [
  "site",
  "iGaming",
  "keyword",
  "GSC",
  "GA4",
  "Ahrefs",
  "Core Update",
  "PBN",
  "Guest Post",
  "Entity",
  "backlink",
  "referring domain",
  "anchor text",
  "expired domain",
  "301 redirect",
  "canonical",
  "indexing",
  "search intent",
  "internal link",
  "organic traffic",
  "money site",
  "negative SEO",
  "disavow",
  "Wayback",
  "casino",
  "betting",
  "sports betting"
] as const;

