export const SEO_IGAMING_GLOSSARY = [
  "site",
  "website",
  "iGaming",
  "keyword",
  "GSC",
  "Google Search Console",
  "GA4",
  "Ahrefs",
  "Semrush",
  "Core Update",
  "PBN",
  "Guest Post",
  "Entity",
  "backlink",
  "referring domain",
  "anchor text",
  "expired domain",
  "301 redirect",
  "canonical",
  "robots.txt",
  "sitemap",
  "indexing",
  "search intent",
  "internal link",
  "DR",
  "UR",
  "organic traffic",
  "money site",
  "negative SEO",
  "disavow",
  "Wayback",
  "casino",
  "betting",
  "sports betting",
  "crawl",
  "bot",
  "SERP",
  "CTR",
  "impression",
  "position",
  "traffic"
] as const;
